# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models.
name: house_construction_project
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: house_construction_project  # Remove `#}` which is incorrect syntax

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:  # Directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  house_construction_project:
    staging:
      +materialized: view
      +snowflake_warehouse: dbt_wh  # Fix: Add `+` before config
    marts:
      +materialized: table
      +snowflake_warehouse: dbt_wh  # Fix: Add `+` before config
